name: Build and Deploy KyooX to Github Pages

on:
  push:
    branches: [$default-branch]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
      - name: Install dev dependencies
        run: npm ci
      - name: Clean before build
        run: npm run clean
      - name: Build KyooX for Github Pages
        run: npm run build -- --pages
      - name: Upload build directory
        uses: actions/upload-pages-artifact@v2
        with:
          name: build
          path: build
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy KyooX to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
        with:
          artifact_name: build